### ISSUE TITLE
dependabot 제거

### ISSUE THREAD

**Issue by KimKyuHoi** [zagdang/design-system#24]
### Summary

- .yml파일 Immutable로 인한 보안 막힘
- zero install가 충돌이 발생함.

### Expected behavior

- 속도를 위해 dependabot.yml파일 제거

### Steps to reproduce the problem

- dependabot.yml 파일 생성후
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/ui"  
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/icons"  
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/colors" 
    schedule:
      interval: "daily"
```
생성후 메인에 머지시 발생함.

### Environment

- Version:
